import './src/components/button/button.js'
import './src/components/tips/tips.js'
import './src/components/slider/slider.js'
import './src/components/select/select.js'
import './src/components/option/option.js'
import './src/components/theme/theme.js'
import './src/components/switch/switch.js'
import './src/components/checkbox/checkbox.js'
import './src/components/radio/radio.js'
import './src/components/radio-group/radio-group.js'
import './src/components/tab-pane/tab-pane.js'
import './src/components/tab/tab.js'
import YMessage from './src/components/message/message.js'
window.$message = YMessage
import YDialog from './src/components/dialog/dialog.js'
window.$dialog = YDialog
import './src/components/input/input.js'
import './src/components/img/img.js'
import './src/components/img-preview/img-preview.js'
import './src/components/rate/rate.js'
