import './components/button/button.js'
import './components/tips/tips.js'
import './components/slider/slider.js'
import './components/select/select.js'
import './components/option/option.js'
import './components/theme/theme.js'
