import './components/button/button.js'
import './components/tips/tips.js'
import './components/slider/slider.js'
import './components/select/select.js'
import './components/option/option.js'
import './components/theme/theme.js'
import './components/switch/switch.js'
import './components/checkbox/checkbox.js'
import './components/radio/radio.js'
import './components/radio-group/radio-group.js'
import './components/tab-pane/tab-pane.js'
import './components/tab/tab.js'
import YMessage from './components/message/message.js'
window.$message = YMessage
import YDialog from './components/dialog/dialog.js'
window.$dialog = YDialog
import './components/input/input.js'
